server.port=8081

# Kafka Configuration
spring.kafka.bootstrap-servers=localhost:9092,localhost:9093,localhost:9094
kafka.topic.message=message-topic

# JSON Configuration
spring.kafka.producer.value-serializer=org.springframework.kafka.support.serializer.JsonSerializer
spring.kafka.producer.key-serializer=org.apache.kafka.common.serialization.StringSerializer

# Application Configuration
spring.application.name=kafka-producer
logging.level.com.example.producer=INFO
logging.level.org.apache.kafka=WARN

# Management endpoints
management.endpoints.web.exposure.include=health,info
management.endpoint.health.show-details=always