apiVersion: v1
kind: ConfigMap
metadata:
  name: demo-app-config
  namespace: default
data:
  application.properties: |
    spring.application.name=demo
    
    # Server configuration
    server.port=8080
    
    # KeyCloak OIDC Configuration
    spring.security.oauth2.client.registration.keycloak.client-id=spring-boot-app
    spring.security.oauth2.client.registration.keycloak.client-secret=uaBzmusHSNtyN9eIdWTqAMwojcqemQI9
    spring.security.oauth2.client.registration.keycloak.scope=openid,profile,email,offline_access
    spring.security.oauth2.client.registration.keycloak.authorization-grant-type=authorization_code
    spring.security.oauth2.client.registration.keycloak.redirect-uri={baseUrl}/login/oauth2/code/{registrationId}
    
    # KeyCloak Provider Configuration - Using K8s service name
    spring.security.oauth2.client.provider.keycloak.issuer-uri=http://keycloak-service:8080/realms/master
    spring.security.oauth2.client.provider.keycloak.user-name-attribute=preferred_username
    
    # Logging for debugging
    logging.level.org.springframework.security=DEBUG
    logging.level.org.springframework.security.oauth2=DEBUG
    
    # Actuator for health checks
    management.endpoints.web.exposure.include=health,info
    management.endpoint.health.show-details=always