apiVersion: apps/v1
kind: Deployment
metadata:
  name: securing-web-deployment
  namespace: securing-web-app
  labels:
    app: securing-web-app
spec:
  replicas: 3
  selector:
    matchLabels:
      app: securing-web-app
  template:
    metadata:
      labels:
        app: securing-web-app
    spec:
      containers:
      - name: securing-web-app
        image: ghcr.io/NguyenPhuongThao05/PhatTrienUDDN/securing-web-app:latest
        ports:
        - containerPort: 8080
        env:
        - name: SPRING_PROFILES_ACTIVE
          value: "mysql"
        - name: SPRING_DATASOURCE_URL
          value: "jdbc:mysql://mysql-service:3306/securedb?useSSL=false&allowPublicKeyRetrieval=true"
        - name: SPRING_DATASOURCE_USERNAME
          valueFrom:
            secretKeyRef:
              name: mysql-secret
              key: mysql-username
        - name: SPRING_DATASOURCE_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mysql-secret
              key: mysql-password
        resources:
          requests:
            memory: "256Mi"
            cpu: "250m"
          limits:
            memory: "512Mi"
            cpu: "500m"
        readinessProbe:
          httpGet:
            path: /actuator/health
            port: 8080
          initialDelaySeconds: 30
          periodSeconds: 10
        livenessProbe:
          httpGet:
            path: /actuator/health
            port: 8080
          initialDelaySeconds: 60
          periodSeconds: 30
---
apiVersion: v1
kind: Service
metadata:
  name: securing-web-service
  namespace: securing-web-app
spec:
  selector:
    app: securing-web-app
  ports:
  - port: 8080
    targetPort: 8080
    nodePort: 30080
  type: NodePort