apiVersion: v1
kind: Secret
metadata:
  name: mysql-secret
  namespace: securing-web-app
type: Opaque
data:
  # root password: rootpassword (base64 encoded)
  mysql-root-password: cm9vdHBhc3N3b3Jk
  # database name: securedb (base64 encoded)
  mysql-database: c2VjdXJlZGI=
  # username: secureuser (base64 encoded)
  mysql-username: c2VjdXJldXNlcg==
  # password: securepass (base64 encoded)
  mysql-password: c2VjdXJlcGFzcw==